import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/NavBar";
import ChangeContent from "@/components/ChangeContent"
import { EdgeStoreProvider } from '../lib/edgestore';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <EdgeStoreProvider>
        {children}
        </EdgeStoreProvider>
        </body>
    </html>
  );
}
